"""
ACHARYA Pure-Python Exam & Study Planner Service
Generates instant, comprehensive Study Roadmaps and Task Plans with 0ms latency.
No AI/LLM dependency required - runs 100% offline & deterministically.
"""
import os
import re
import subprocess

class PlannerService:
    def create_plan(self, query: str, user_identity: dict = None) -> dict:
        """
        Generates a rich 5-phase Exam Preparation & Study Roadmap using Pure Python.
        Saves the file to Desktop, opens it asynchronously, and returns structured phases for UI rendering.
        """
        clean_topic = re.sub(r'^(?:help me in|help me|learn|learning|teach me|how to|plan|create plan|study plan|prepare for|planner|schedule)\s+', '', query, flags=re.IGNORECASE).strip()
        if not clean_topic:
            clean_topic = "Exam Preparation & Daily Mastery"

        topic_display = clean_topic.title()
        safe_filename = re.sub(r'[^\w\s-]', '', clean_topic).strip().replace(' ', '_')
        if not safe_filename:
            safe_filename = "Study_Plan"
        plan_filename = f"ACHARYA_PLAN_{safe_filename}.md"

        desktop_dir = os.path.join(os.path.expanduser("~"), "Desktop")
        file_path = os.path.join(desktop_dir, plan_filename)

        phases = [
            {"phase": "Phase 1", "title": "Core Fundamentals", "task": f"Review primary syllabus & definitions for {topic_display}"},
            {"phase": "Phase 2", "title": "Targeted Practice", "task": f"Solve 10-15 standard practice problems in {topic_display}"},
            {"phase": "Phase 3", "title": "Simulated Mock Exam", "task": f"Complete timed speed run under test conditions"},
            {"phase": "Phase 4", "title": "Memory Consolidation", "task": f"Audit weak spots & review Feynman summary sheet"},
            {"phase": "Phase 5", "title": "Execution Strategy", "task": f"Final review & optimal performance preparation"}
        ]

        markdown_content = f"""# 🎯 ACHARYA OS — Study & Exam Preparation Roadmap: {topic_display}

> **Target Objective**: Complete Mastery & High-Performance Execution in `{topic_display}`
> **Status**: Active Preparation Mode

---

## 📌 Phase 1: Core Fundamentals & Concept Mapping (Days 1 - 2)
- [ ] **Review Primary Syllabus**: Identify core definitions, theorems, and primary frameworks for {topic_display}.
- [ ] **Active Recall Sheet**: Create 15-20 core question prompts without looking at notes.
- [ ] **Terminology Audit**: Ensure 100% fluency with essential technical jargon.

## ⚡ Phase 2: Targeted Practice & Problem Solving (Days 3 - 4)
- [ ] **High-ROI Practice Questions**: Solve 10-15 standard exam/interview-style problems in {topic_display}.
- [ ] **Feynman Technique**: Explain key concepts out loud in simple terms without notes.
- [ ] **Error Log Analysis**: Document every mistake made during practice and write the correct solution.

## 🚀 Phase 3: Simulated Mock Exam & Speed Run (Day 5)
- [ ] **Timed Mock Session**: Complete a timed practice test under strict exam conditions.
- [ ] **Weakness Audit**: Flag any topic where confidence scored under 80%.

## 🎯 Phase 4: Final Polish & Memory Consolidation (Day 6)
- [ ] **Formula / Summary Sheet Review**: Skim condensed key takeaways and cheat sheets.
- [ ] **Spaced Repetition Flashcards**: Quick 20-minute memory audit before rest.

## 🏆 Phase 5: Execution Day Strategy
- [ ] Sleep minimum 7.5 hours prior to exam.
- [ ] Read all questions twice before writing answers.

---
*Generated by ACHARYA OS Pure-Python Planner Engine*
"""

        try:
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(markdown_content)
        except Exception as e:
            print(f"[PlannerService] Error writing plan file: {e}")

        # Non-blocking async file opening on Windows
        try:
            subprocess.Popen(f'start "" "{file_path}"', shell=True)
        except Exception:
            pass

        return {
            "title": f"Study Roadmap: {topic_display}",
            "summary": f"Generated 5-phase preparation roadmap for {topic_display}.",
            "speech": f"Sir, I have generated your customized study and preparation roadmap for {topic_display} and opened it from your Desktop.",
            "markdown_plan": markdown_content,
            "phases": phases,
            "file_path": file_path
        }
